"""empty message

Revision ID: 700024032f4f
Revises: b4772e3b4105
Create Date: 2023-09-28 19:54:51.947796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '700024032f4f'
down_revision = 'b4772e3b4105'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
