# Generated by Django 4.2.6 on 2023-10-19 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Qestion",
            new_name="Question",
        ),
    ]
