version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - "8000:8000"
    container_name: app_users
    restart: unless-stopped
    networks:
      - app-networks
  db:
    image: mongo
    container_name: db
    restart: unless-stopped

      - serviceName
    volumes:
      - /tmp/mongo-data:/data/db
    networks:
      - app-networks
networks:
  app-networks:
    driver: bridge